# ===================================
#  List Behavior Config
# ===================================

list: $/numencode/widgets/models/featuregroup/columns.yaml
modelClass: NumenCode\Widgets\Models\FeatureGroup
title: 'numencode.widgets::lang.features.manage'
noRecordsMessage: 'backend::lang.list.no_records'
recordUrl: 'numencode/widgets/features/update/:id'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
showPageNumbers: true
showSorting: true
defaultSort:
    column: title
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
